---
- hosts: all
  become: true
  become_method: sudo
  roles:
  # - placeholder

  tasks:

    - name: Install base
      apt:
        update_cache: yes
        name: "{{ item }}"
        state: present
      with_items:
        - realvnc-vnc-server
        - realvnc-vnc-viewer
        - vim
      tags: [ "base" ]

    - name: generate /etc/lightdm/lightdm.conf
      template:
        src: lightdm.conf.j2
        dest: /etc/lightdm/lightdm.conf
        owner: root
        group: root
        mode: 0644


#   - name: install distrubute
#     pip: name=distribute
#     tags: [ "pip","package" ]
#
#   - name: Download BFR from github
#     git:
#       repo=git://github.com/mushorg/BFR.git
#       dest=/opt/BFR
#     register: bfr
#     tags: [ "git" ]
# 
#   - name: Make BFR
#     shell: "{{item}}"
#     args:
#       chdir: /opt/BFR/
#     with_items:
#       - phpize
#       - ./configure --enable-bfr
#       - make
#       - make install
#     when: bfr.changed
# 
#   - name: Find bfr.so path
#     shell: updatedb && locate bfr.so | grep usr
#     register: bfr_path
#     # when: bfr.changed
# 
#   - name: Generate php.ini
#     template:
#       src=templates/php.ini.j2
#       dest=/etc/php/7.0/cli/php.ini
#       owner=root
#       group=root
#       mode=0600
#     # when: bfr.changed
# 
#   - name: Download glastopf from github
#     git:
#       repo=https://github.com/mushorg/glastopf.git
#       dest=/opt/glastopf
#     register: glastopf
#     tags: [ "git" ]
# 
#   - name: Install glastopf
#     shell: python setup.py install
#     args:
#       chdir: /opt/glastopf
#     when: glastopf.changed
# 
#   - name: Configure glastopf environment
#     file:
#       path=/opt/myhoneypot
#       state=directory
#       mode=0755
# 
#   - name: Generate glastopf.cfg
#     template:
#       src=glastopf.cfg.j2
#       dest=/opt/myhoneypot/glastopf.cfg
#     tags: [ "config" ]
# 
#   - name: Start glastopf-runner (IGNORE ERRORS)
#     become: false
#     ignore_errors: yes
#     shell: nohup /usr/bin/python /usr/local/bin/glastopf-runner &
#     args:
#       executable: /bin/bash
#       chdir: /opt/myhoneypot
#     poll: 0
